# Generated by Django 4.2.5 on 2023-11-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_group_remove_task_content_remove_task_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='context',
            field=models.CharField(default='', max_length=100),
        ),
    ]
