# Generated by Django 4.2.5 on 2023-11-19 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_rename_user_profile_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_by',
            new_name='user',
        ),
    ]
